using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AutoLog;

[Generator]
public sealed class AutoLogGenerator : IIncrementalGenerator
{
    private const string AttributeSource = @"// <auto-generated by AutoLog.Generator/>
#nullable enable
using System;
using Microsoft.Extensions.Logging;

namespace AutoLog
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public sealed class LogAttribute : Attribute
    {
        public LogLevel Level { get; }
        public string Message { get; }
        public int EventId { get; set; } = 0;

        public LogAttribute(LogLevel level, string message)
        {
            Level = level;
            Message = message;
        }
    }
}
";

    private static readonly DiagnosticDescriptor AL001 = new(
        id: "AL001",
        title: "Log method must be partial void",
        messageFormat: "[Log] on '{0}' in '{1}' — method must be `partial void`.",
        category: "AutoLog",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AL002 = new(
        id: "AL002",
        title: "No ILogger found",
        messageFormat: "[Log] on '{0}' — containing class '{1}' has no `ILogger` or `ILogger<T>` field or property. Add one to enable log generation.",
        category: "AutoLog",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor AL003 = new(
        id: "AL003",
        title: "Too many log parameters",
        messageFormat: "[Log] on '{0}' has {1} type parameters — LoggerMessage.Define supports a maximum of 6.",
        category: "AutoLog",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly SymbolDisplayFormat FullyQualifiedTypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
            SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("AutoLog.Attributes.g.cs", AttributeSource));

        var logMethods = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "AutoLog.LogAttribute",
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) => Transform(ctx))
            .Where(static candidate => candidate is not null)
            .Select(static (candidate, _) => candidate!);

        context.RegisterSourceOutput(logMethods.Collect(), static (ctx, methods) => Generate(ctx, methods));
    }

    private static LogMethodCandidate? Transform(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not IMethodSymbol methodSymbol ||
            context.TargetNode is not MethodDeclarationSyntax methodSyntax)
        {
            return null;
        }

        var attribute = context.Attributes[0];
        var containingType = methodSymbol.ContainingType;

        var levelExpression = GetLevelExpression(attribute.ConstructorArguments[0]);
        var message = attribute.ConstructorArguments[1].Value as string ?? string.Empty;
        var eventId = 0;
        foreach (var namedArgument in attribute.NamedArguments)
        {
            if (namedArgument.Key == "EventId" && namedArgument.Value.Value is int explicitEventId)
            {
                eventId = explicitEventId;
                break;
            }
        }

        return new LogMethodCandidate(
            containingType,
            methodSymbol,
            methodSyntax,
            levelExpression,
            message,
            eventId,
            methodSymbol.Locations.FirstOrDefault() ?? containingType.Locations.FirstOrDefault() ?? Location.None);
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<LogMethodCandidate> candidates)
    {
        if (candidates.IsDefaultOrEmpty)
        {
            return;
        }

        var grouped = new Dictionary<INamedTypeSymbol, List<LogMethodCandidate>>(SymbolEqualityComparer.Default);
        foreach (var candidate in candidates)
        {
            if (!grouped.TryGetValue(candidate.ContainingType, out var list))
            {
                list = new List<LogMethodCandidate>();
                grouped.Add(candidate.ContainingType, list);
            }

            list.Add(candidate);
        }

        foreach (var entry in grouped)
        {
            var containingType = entry.Key;
            var orderedCandidates = entry.Value
                .OrderBy(static method => method.Location.SourceSpan.Start)
                .ToList();

            var loggerMemberName = FindLoggerMemberName(containingType);
            var methodsToGenerate = new List<GeneratedMethod>();
            var nextAutoEventId = 1;

            foreach (var candidate in orderedCandidates)
            {
                if (!IsSupportedPartialMethod(candidate.MethodSymbol, candidate.MethodSyntax) || !IsInPartialClassChain(containingType))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        AL001,
                        candidate.Location,
                        candidate.MethodSymbol.Name,
                        containingType.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)));
                    continue;
                }

                if (loggerMemberName is null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        AL002,
                        candidate.Location,
                        candidate.MethodSymbol.Name,
                        containingType.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat)));
                    continue;
                }

                var generatedMethod = CreateGeneratedMethod(candidate, candidate.ExplicitEventId > 0 ? candidate.ExplicitEventId : nextAutoEventId);
                nextAutoEventId++;

                if (generatedMethod.LogParameterCount > 6)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        AL003,
                        candidate.Location,
                        candidate.MethodSymbol.Name,
                        generatedMethod.LogParameterCount));
                }

                methodsToGenerate.Add(generatedMethod);
            }

            if (methodsToGenerate.Count == 0 || loggerMemberName is null)
            {
                continue;
            }

            context.AddSource(GetHintName(containingType), RenderContainingType(containingType, loggerMemberName, methodsToGenerate));
        }
    }

    private static GeneratedMethod CreateGeneratedMethod(LogMethodCandidate candidate, int eventId)
    {
        var parameters = candidate.MethodSymbol.Parameters
            .Select(static parameter => new MethodParameter(
                parameter.Name,
                parameter.Type.ToDisplayString(FullyQualifiedTypeFormat),
                parameter.RefKind))
            .ToImmutableArray();

        var exceptionParameterName = default(string);
        if (candidate.MethodSymbol.Parameters.Length > 0)
        {
            var lastParameter = candidate.MethodSymbol.Parameters[candidate.MethodSymbol.Parameters.Length - 1];
            if (IsExceptionType(lastParameter.Type))
            {
                exceptionParameterName = lastParameter.Name;
            }
        }

        var logParameterNames = new List<string>();
        var logParameterTypes = new List<string>();

        foreach (var parameter in candidate.MethodSymbol.Parameters)
        {
            if (parameter.Name == exceptionParameterName)
            {
                continue;
            }

            logParameterNames.Add(parameter.Name);
            logParameterTypes.Add(parameter.Type.ToDisplayString(FullyQualifiedTypeFormat));
        }

        return new GeneratedMethod(
            candidate.MethodSymbol.Name,
            candidate.MethodSyntax.Modifiers.ToFullString().Trim(),
            parameters,
            candidate.LevelExpression,
            candidate.Message,
            eventId,
            exceptionParameterName,
            logParameterNames.ToImmutableArray(),
            logParameterTypes.ToImmutableArray());
    }

    private static string RenderContainingType(
        INamedTypeSymbol containingType,
        string loggerMemberName,
        IReadOnlyList<GeneratedMethod> methods)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by AutoLog.Generator/>");
        builder.AppendLine("#nullable enable");

        var indentLevel = 0;
        if (!containingType.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ");
            builder.AppendLine(containingType.ContainingNamespace.ToDisplayString());
            builder.AppendLine("{");
            indentLevel++;
        }

        var typeChain = GetContainingTypeChain(containingType);
        foreach (var type in typeChain)
        {
            AppendIndent(builder, indentLevel);
            builder.Append("partial class ");
            builder.Append(type.Name);
            builder.AppendLine(GetTypeParameters(type));
            AppendIndent(builder, indentLevel);
            builder.AppendLine("{");
            indentLevel++;
        }

        for (var i = 0; i < methods.Count; i++)
        {
            RenderMethod(builder, indentLevel, loggerMemberName, methods[i]);

            if (i < methods.Count - 1)
            {
                builder.AppendLine();
            }
        }

        for (var i = typeChain.Count - 1; i >= 0; i--)
        {
            indentLevel--;
            AppendIndent(builder, indentLevel);
            builder.AppendLine("}");
        }

        if (!containingType.ContainingNamespace.IsGlobalNamespace)
        {
            indentLevel--;
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void RenderMethod(StringBuilder builder, int indentLevel, string loggerMemberName, GeneratedMethod method)
    {
        var actionFieldName = GetActionFieldName(method.MethodName);

        AppendIndent(builder, indentLevel);
        builder.Append("private static readonly ");
        builder.Append(GetDelegateType(method));
        builder.Append(' ');
        builder.Append(actionFieldName);
        builder.AppendLine(" =");

        AppendIndent(builder, indentLevel + 1);
        builder.AppendLine(GetDelegateFactory(method));

        builder.AppendLine();

        AppendIndent(builder, indentLevel);
        if (!string.IsNullOrWhiteSpace(method.ModifiersText))
        {
            builder.Append(method.ModifiersText);
            builder.Append(' ');
        }

        builder.Append("void ");
        builder.Append(method.MethodName);
        builder.Append('(');
        builder.Append(string.Join(", ", method.Parameters.Select(FormatParameter)));
        builder.AppendLine(")");

        AppendIndent(builder, indentLevel + 1);
        builder.Append("=> ");
        builder.Append(actionFieldName);
        builder.Append('(');
        builder.Append(loggerMemberName);

        if (method.LogParameterCount > 6)
        {
            builder.Append(", new object?[] { ");
            builder.Append(string.Join(", ", method.LogParameterNames));
            builder.Append(" }");
        }
        else
        {
            foreach (var parameterName in method.LogParameterNames)
            {
                builder.Append(", ");
                builder.Append(parameterName);
            }
        }

        builder.Append(", ");
        builder.Append(method.ExceptionParameterName ?? "null");
        builder.AppendLine(");");
    }

    private static string GetDelegateType(GeneratedMethod method)
    {
        if (method.LogParameterCount > 6)
        {
            return "global::System.Action<global::Microsoft.Extensions.Logging.ILogger, object?[], global::System.Exception?>";
        }

        var builder = new StringBuilder("global::System.Action<global::Microsoft.Extensions.Logging.ILogger");
        foreach (var typeName in method.LogParameterTypes)
        {
            builder.Append(", ");
            builder.Append(typeName);
        }

        builder.Append(", global::System.Exception?>");
        return builder.ToString();
    }

    private static string GetDelegateFactory(GeneratedMethod method)
    {
        var messageLiteral = Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(method.Message, true);
        var eventIdExpression = $"new global::Microsoft.Extensions.Logging.EventId({method.EventId}, {Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(method.MethodName, true)})";

        if (method.LogParameterCount > 6)
        {
            return
                $"static (logger, args, exception) => global::Microsoft.Extensions.Logging.LoggerExtensions.Log(logger, {method.LevelExpression}, {eventIdExpression}, exception, {messageLiteral}, args);";
        }

        if (method.LogParameterCount == 0)
        {
            return $"global::Microsoft.Extensions.Logging.LoggerMessage.Define({method.LevelExpression}, {eventIdExpression}, {messageLiteral});";
        }

        return
            $"global::Microsoft.Extensions.Logging.LoggerMessage.Define<{string.Join(", ", method.LogParameterTypes)}>({method.LevelExpression}, {eventIdExpression}, {messageLiteral});";
    }

    private static string FormatParameter(MethodParameter parameter)
    {
        var refPrefix = parameter.RefKind switch
        {
            RefKind.In => "in ",
            RefKind.Out => "out ",
            RefKind.Ref => "ref ",
            _ => string.Empty
        };

        return $"{refPrefix}{parameter.TypeName} {parameter.Name}";
    }

    private static string? FindLoggerMemberName(INamedTypeSymbol containingType)
    {
        foreach (var member in containingType.GetMembers())
        {
            switch (member)
            {
                case IFieldSymbol field when !field.IsStatic && IsLoggerType(field.Type):
                    return field.Name;
                case IPropertySymbol property when !property.IsStatic && IsLoggerType(property.Type):
                    return property.Name;
            }
        }

        return null;
    }

    private static bool IsLoggerType(ITypeSymbol type)
    {
        if (type is not INamedTypeSymbol namedType)
        {
            return false;
        }

        var metadataName = namedType.OriginalDefinition.ToDisplayString();
        return metadataName is "Microsoft.Extensions.Logging.ILogger" or "Microsoft.Extensions.Logging.ILogger<TCategoryName>";
    }

    private static bool IsSupportedPartialMethod(IMethodSymbol methodSymbol, MethodDeclarationSyntax methodSyntax)
    {
        return methodSymbol.MethodKind == MethodKind.Ordinary &&
               !methodSymbol.IsStatic &&
               methodSymbol.ReturnsVoid &&
               methodSymbol.IsPartialDefinition &&
               methodSymbol.PartialImplementationPart is null &&
               methodSyntax.Body is null &&
               methodSyntax.ExpressionBody is null;
    }

    private static bool IsInPartialClassChain(INamedTypeSymbol typeSymbol)
    {
        for (var current = typeSymbol; current is not null; current = current.ContainingType)
        {
            if (current.TypeKind != TypeKind.Class)
            {
                return false;
            }

            var isPartial = current.DeclaringSyntaxReferences
                .Select(static syntaxReference => syntaxReference.GetSyntax())
                .OfType<ClassDeclarationSyntax>()
                .Any(static syntax => syntax.Modifiers.Any(static modifier => modifier.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)));

            if (!isPartial)
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsExceptionType(ITypeSymbol type)
    {
        for (var current = type; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == "System.Exception")
            {
                return true;
            }
        }

        return false;
    }

    private static string GetLevelExpression(TypedConstant constant)
    {
        if (constant.Type is INamedTypeSymbol enumType && constant.Value is not null)
        {
            var member = enumType.GetMembers()
                .OfType<IFieldSymbol>()
                .FirstOrDefault(field => field.HasConstantValue && Equals(field.ConstantValue, constant.Value));

            if (member is not null)
            {
                return $"{enumType.ToDisplayString(FullyQualifiedTypeFormat)}.{member.Name}";
            }

            return $"({enumType.ToDisplayString(FullyQualifiedTypeFormat)}){constant.Value}";
        }

        return "global::Microsoft.Extensions.Logging.LogLevel.Information";
    }

    private static string GetHintName(INamedTypeSymbol type)
    {
        var parts = new Stack<string>();
        for (var current = type; current is not null; current = current.ContainingType)
        {
            parts.Push(current.Name);
        }

        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            parts.Push(type.ContainingNamespace.ToDisplayString().Replace('.', '_'));
        }

        return string.Join("_", parts) + ".AutoLog.g.cs";
    }

    private static List<INamedTypeSymbol> GetContainingTypeChain(INamedTypeSymbol type)
    {
        var chain = new List<INamedTypeSymbol>();
        for (var current = type; current is not null; current = current.ContainingType)
        {
            chain.Add(current);
        }

        chain.Reverse();
        return chain;
    }

    private static string GetTypeParameters(INamedTypeSymbol type)
        => type.TypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", type.TypeParameters.Select(static parameter => parameter.Name)) + ">";

    private static string GetActionFieldName(string methodName)
        => "_" + char.ToLowerInvariant(methodName[0]) + methodName.Substring(1) + "Action";

    private static void AppendIndent(StringBuilder builder, int level)
        => builder.Append(' ', level * 4);

    private sealed class LogMethodCandidate
    {
        public LogMethodCandidate(
            INamedTypeSymbol containingType,
            IMethodSymbol methodSymbol,
            MethodDeclarationSyntax methodSyntax,
            string levelExpression,
            string message,
            int explicitEventId,
            Location location)
        {
            ContainingType = containingType;
            MethodSymbol = methodSymbol;
            MethodSyntax = methodSyntax;
            LevelExpression = levelExpression;
            Message = message;
            ExplicitEventId = explicitEventId;
            Location = location;
        }

        public INamedTypeSymbol ContainingType { get; }
        public IMethodSymbol MethodSymbol { get; }
        public MethodDeclarationSyntax MethodSyntax { get; }
        public string LevelExpression { get; }
        public string Message { get; }
        public int ExplicitEventId { get; }
        public Location Location { get; }
    }

    private sealed class MethodParameter
    {
        public MethodParameter(string name, string typeName, RefKind refKind)
        {
            Name = name;
            TypeName = typeName;
            RefKind = refKind;
        }

        public string Name { get; }
        public string TypeName { get; }
        public RefKind RefKind { get; }
    }

    private sealed class GeneratedMethod
    {
        public GeneratedMethod(
            string methodName,
            string modifiersText,
            ImmutableArray<MethodParameter> parameters,
            string levelExpression,
            string message,
            int eventId,
            string? exceptionParameterName,
            ImmutableArray<string> logParameterNames,
            ImmutableArray<string> logParameterTypes)
        {
            MethodName = methodName;
            ModifiersText = modifiersText;
            Parameters = parameters;
            LevelExpression = levelExpression;
            Message = message;
            EventId = eventId;
            ExceptionParameterName = exceptionParameterName;
            LogParameterNames = logParameterNames;
            LogParameterTypes = logParameterTypes;
        }

        public string MethodName { get; }
        public string ModifiersText { get; }
        public ImmutableArray<MethodParameter> Parameters { get; }
        public string LevelExpression { get; }
        public string Message { get; }
        public int EventId { get; }
        public string? ExceptionParameterName { get; }
        public ImmutableArray<string> LogParameterNames { get; }
        public ImmutableArray<string> LogParameterTypes { get; }
        public int LogParameterCount => LogParameterNames.Length;
    }
}
